version: '2'

services:
  djangoproject:
    build: ./cloudberry-djangoproject
    environment:
      DOCKER_MANAGER_UUID: "d23eba83-fc94-4ede-90fe-34a7ceb468e9"
      DOCKER_MANAGER_KEY: "ufZvOiPh5EWp6kRH8if2oX4Wysx0WwS0"
    ports:
      - 8000:80
    networks:
      - elk
    depends_on:
      - db

  docker-manager:
    build:
      context: cloudberry-docker-manager
    environment:
      OPENWISP_URL: "http://djangoproject"
      OPENWISP_UUID: "d23eba83-fc94-4ede-90fe-34a7ceb468e9"
      OPENWISP_KEY: "ufZvOiPh5EWp6kRH8if2oX4Wysx0WwS0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk
    depends_on:
      - djangoproject

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - elk

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - radiuslogs:/radiuslogs
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  radius:
    build:
      context: radius/
    volumes:
      - radiuslogs:/var/log/detail_authlog
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    networks:
      - elk
    depends_on:
      - db

networks:
  elk:
    driver: bridge

volumes:
  radiuslogs:
  database:
